Repository ponylang/regex, pull requests merged in 2022-02, with the labels that each got.

#36 Add nodoc annotation to test code
  regex/_test.pony
Labels: discuss during sync

#37 Update prce2 download location
  .release-notes/37.md
  make.ps1
Labels: changelog - fixed, discuss during sync

#39 Support for using ponyup on Windows
  .release-notes/39.md
  make.ps1
Labels: changelog - added, discuss during sync

#40 Update to address PonyTest package being renamed
  .github/workflows/pr.yml
  .release-notes/ponytest.md
  regex/_test.pony
Labels: changelog - fixed, discuss during sync

#41 Remove hardcoded Visual Studio version
  .release-notes/vs.md
  README.md
  make.ps1
Labels: changelog - fixed, discuss during sync

#42 Run PRs against release builds again
  .github/workflows/pr.yml
Labels: discuss during sync
